### ISSUE TITLE
`SVGDefault::circle` sets `radius` instead of `r`

### ISSUE THREAD

**Issue by marfl** [coastalwhite/WasmSVGGraphics#2]
Hi! I was following the very first example in the docs, ending up with a white page (no circle). After some digging, the problem seems to be that the `SVGDefault::circle` function sets the `radius` attribute of the SVG element, while the SVG standard expects the radius of a circle to be set via the `r` attribute. Hence, `circle` currently only draws circles with radius 0.

**Comment by coastalwhite** [comment]
Yeah, that is indeed true. I suspect that at the time this library was initially written the SVG 1.0 standard was still in effect. It is now indeed updated with PR #3 and in version 1.0.4.

**Comment by marfl** [comment]
Thanks!
